CRITICAL - 2020-11-04 07:37:04 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:37:36 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:37:37 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:46:44 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:46:46 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:46:47 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:20 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:23 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:26 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:28 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:43 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:48:45 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:49:44 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:51:04 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:54:41 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:29 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:32 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:33 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:34 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:34 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:34 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:34 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:35 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:35 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:35 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 07:55:35 --> Unable to connect to the database.
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2019): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\Apache24\htdocs\rosas\app\Models\Querys.php(18): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\Apache24\htdocs\rosas\app\Helpers\Rosas_helper.php(8): App\Models\Querys->view_users(Array)
#4 C:\Apache24\htdocs\rosas\app\Controllers\BaseController.php(48): authenticated()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(891): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#7 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-11-04 08:03:10 --> Invalid file: home.php
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('home', Array, true)
#2 C:\Apache24\htdocs\rosas\app\Libraries\Templater.php(34): view('home', Array)
#3 C:\Apache24\htdocs\rosas\app\Controllers\Home.php(10): App\Libraries\Templater->view('home', Array)
#4 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-11-04 08:03:26 --> Invalid file: home.php
#0 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('home.php')
#1 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('home', Array, true)
#2 C:\Apache24\htdocs\rosas\app\Libraries\Templater.php(34): view('home', Array)
#3 C:\Apache24\htdocs\rosas\app\Controllers\Home.php(10): App\Libraries\Templater->view('home', Array)
#4 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Home->index()
#5 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\Apache24\htdocs\rosas\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Apache24\htdocs\rosas\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
